### ISSUE TITLE
cd command

### ISSUE THREAD

**Issue by jschvartz** [ak9250/gpt-2-colab#1]
Works great, thanks.
I've just been confused by the missing 

> **%**

 before the **cd** commands ...
(brand new to colab ...)

**Comment by ak9250** [comment]
you can use %cd as well, both cd and %cd should work

**Comment by jschvartz** [comment]
Oh yes, i can see that now ...
I was too quick, and wanted to make a multiple line cell code. In that case cd alone don't work (considered as a python instruction, i guess)
But your instructions are clear enougth ;-)
