### ISSUE TITLE
Getting this error ZeroDivisionError: integer division or modulo by zero while training 

### ISSUE THREAD

**Issue by aliasgar1530** [ak9250/gpt-2-colab#10]
Im getting error while training on this cell
`!PYTHONPATH=src ./train.py --dataset /content/gpt-2/goblet_book.txt --model_name '345M'`
`Traceback (most recent call last):
  File "./train.py", line 266, in <module>
    main()
  File "./train.py", line 244, in main
    feed_dict={context: sample_batch()})
  File "./train.py", line 220, in sample_batch
    return [data_sampler.sample(1024) for _ in range(args.batch_size)]
  File "./train.py", line 220, in <listcomp>
    return [data_sampler.sample(1024) for _ in range(args.batch_size)]
  File "/content/gpt-2/src/load_dataset.py", line 74, in sample
    self.chunks
ZeroDivisionError: integer division or modulo by zero`

**Comment by gsarti** [comment]
You don't have a goblet_book.txt file in your drive, don't you? @ak9250 forgot to change the train string after changing the previous file in the wget command from the "Goblet of Fire" to "A Tale of Two Cities". 

Just change the command to `!PYTHONPATH=src ./train.py --dataset /content/gpt-2/98-0.txt --model_name '345M'` for testing the notebook, this should be fixed soon! :smiley:

**Comment by ak9250** [comment]
@aliasgar1530  I have added the fix thanks for opening issue and @gsarti thanks for replying with the fix

**Comment by aliasgar1530** [comment]
it fixed now
thanks
